[package]
name = "agent"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
tokio.workspace = true
thiserror.workspace = true
tonic.workspace = true
anyhow.workspace = true
tracing.workspace = true
tokio-stream.workspace = true

proto = { workspace = true, features = ["client"] }
