[package]
name = "proto"
version.workspace = true
edition.workspace = true
publish.workspace = true

[features]
client = []
server = []

[dependencies]
prost = { workspace = true, features = ["default", "derive", "no-recursion-limit", "std"] }
prost-types.workspace = true
tonic.workspace = true
tonic-prost.workspace = true

[build-dependencies]
tonic-prost-build.workspace = true
